//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnBo.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnBo.Core.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 15 menu items are not supported.
        /// </summary>
        internal static string ConsoleMenuMoreThan15MenuItemsAreNotSupported {
            get {
                return ResourceManager.GetString("ConsoleMenuMoreThan15MenuItemsAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access violation..
        /// </summary>
        internal static string ErrorAccessViolation {
            get {
                return ResourceManager.GetString("ErrorAccessViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is not valid. The specified path {1} is too long. The directory name must be less than 248 characters..
        /// </summary>
        internal static string ErrorArgDirectoryPathToLongTemplate2Args {
            get {
                return ResourceManager.GetString("ErrorArgDirectoryPathToLongTemplate2Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is not valid. The specified file name {1} is too long. The fully qualified file name must be less than 260 characters..
        /// </summary>
        internal static string ErrorArgFilePathToLongTemplate2Args {
            get {
                return ResourceManager.GetString("ErrorArgFilePathToLongTemplate2Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path {1} provided by argument {0} does not exist..
        /// </summary>
        internal static string ErrorArgumentDirectoryPathExceptionTemplate2Args {
            get {
                return ResourceManager.GetString("ErrorArgumentDirectoryPathExceptionTemplate2Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path {1} provided by argument {0} does not exist..
        /// </summary>
        internal static string ErrorArgumentFilePathExceptionTemplate2Args {
            get {
                return ResourceManager.GetString("ErrorArgumentFilePathExceptionTemplate2Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} may not be empty..
        /// </summary>
        internal static string ErrorArgumentNotEmptyValidationTemplate1Arg {
            get {
                return ResourceManager.GetString("ErrorArgumentNotEmptyValidationTemplate1Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is out of range (Value: {1})..
        /// </summary>
        internal static string ErrorArgumentOutOfRangeValidationTemplate4Args {
            get {
                return ResourceManager.GetString("ErrorArgumentOutOfRangeValidationTemplate4Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is out of range [{2} &lt;= Value: {1} &lt;= {3}]..
        /// </summary>
        internal static string ErrorArgumentOutOfRangeValidationWithRangeTemplate4Args {
            get {
                return ResourceManager.GetString("ErrorArgumentOutOfRangeValidationWithRangeTemplate4Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is not valid..
        /// </summary>
        internal static string ErrorArgumentTemplate1Arg {
            get {
                return ResourceManager.GetString("ErrorArgumentTemplate1Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument validation failed ({0}: {1}).
        /// </summary>
        internal static string ErrorArgumentValidationFailedTemplate2Args {
            get {
                return ResourceManager.GetString("ErrorArgumentValidationFailedTemplate2Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business rule violation..
        /// </summary>
        internal static string ErrorBusinessRuleViolation {
            get {
                return ResourceManager.GetString("ErrorBusinessRuleViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path is too long. The directory name must be less than 248 characters..
        /// </summary>
        internal static string ErrorDirectoryPathToLong {
            get {
                return ResourceManager.GetString("ErrorDirectoryPathToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file name is too long. The fully qualified file name must be less than 260 characters..
        /// </summary>
        internal static string ErrorFilePathToLong {
            get {
                return ResourceManager.GetString("ErrorFilePathToLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure in infrastructure/system..
        /// </summary>
        internal static string ErrorInfrastructureOrSystem {
            get {
                return ResourceManager.GetString("ErrorInfrastructureOrSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object state permits execution of operation &apos;{0}&apos;..
        /// </summary>
        internal static string ErrorInvalidOperationRequestTemplate1Arg {
            get {
                return ResourceManager.GetString("ErrorInvalidOperationRequestTemplate1Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation execution failed (operation: {0}). .
        /// </summary>
        internal static string ErrorOperationExecutionFailedTemplate1Arg {
            get {
                return ResourceManager.GetString("ErrorOperationExecutionFailedTemplate1Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} may not be null or empty (Value: {1})..
        /// </summary>
        internal static string ErrorShouldNotBeNullOrEmptyValidationTemplate2Args {
            get {
                return ResourceManager.GetString("ErrorShouldNotBeNullOrEmptyValidationTemplate2Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} may not be null..
        /// </summary>
        internal static string ErrorShouldNotBeNullValidationTemplate1Arg {
            get {
                return ResourceManager.GetString("ErrorShouldNotBeNullValidationTemplate1Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} cannot be assigned to variables of type {1}..
        /// </summary>
        internal static string ErrorTypesAreNotAssignableTemplate2Args {
            get {
                return ResourceManager.GetString("ErrorTypesAreNotAssignableTemplate2Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32 error {0} occured during {1} execution..
        /// </summary>
        internal static string ErrorWin32ExecutionFailedTemplate2Args {
            get {
                return ResourceManager.GetString("ErrorWin32ExecutionFailedTemplate2Args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of elements to copy is greater than the available space in the destination array..
        /// </summary>
        internal static string TrackedCollectionArrayTooSmall {
            get {
                return ResourceManager.GetString("TrackedCollectionArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection was modified after the enumerator was created..
        /// </summary>
        internal static string TrackedCollectionEnumHasChanged {
            get {
                return ResourceManager.GetString("TrackedCollectionEnumHasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The enumerator is positioned before the first element of the collection or after the last element..
        /// </summary>
        internal static string TrackedCollectionEnumInvalidPos {
            get {
                return ResourceManager.GetString("TrackedCollectionEnumInvalidPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified index is greater than or equal to than the length of the destination array..
        /// </summary>
        internal static string TrackedCollectionIndexNotInArray {
            get {
                return ResourceManager.GetString("TrackedCollectionIndexNotInArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination array must be one-dimensional..
        /// </summary>
        internal static string TrackedCollectionNotOneDimensional {
            get {
                return ResourceManager.GetString("TrackedCollectionNotOneDimensional", resourceCulture);
            }
        }
    }
}
